name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Remove existing virtual environment
      run: |
        if [ -d ".venv" ]; then rm -rf .venv; fi

    - name: Install virtualenv
      run: |
        pip install virtualenv

    - name: Install dependencies
      run: |
        virtualenv .venv
        . .venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        . .venv/bin/activate
        python -m unittest discover -s tests

    - name: Start Flask app
      run: |
        . .venv/bin/activate
        nohup python mypython.py &> flask.log &

    - name: Wait for Flask to start
      run: sleep 20

    - name: Check Flask logs
      run: |
        cat flask.log

    - name: Test Flask app
      run: |
        curl -f http://localhost:5001/

    - name: Stop Flask app
      run: |
        pkill -f "python mypython.py"
